export { jsonProductRepo as productRepo } from "./products.repository";
export { jsonCategoryRepo as categoryRepo } from "./categories.repository";
export { jsonUserRepo as userRepo } from "./users.repository";
export { jsonOrderRepo as orderRepo } from "./orders.repository";
export { jsonPaymentRepo as paymentRepo } from "./payments.repository";
export { jsonAddressRepo as addressRepo } from "./addresses.repository";
export { jsonWishlistRepo as wishlistRepo } from "./wishlists.repository";
export { jsonCartRepo as cartRepo } from "./carts.repository";
export { jsonReviewRepo as reviewRepo } from "./reviews.repository";
export { jsonCouponRepo as couponRepo } from "./coupons.repository";
export { jsonAbandonedCartRepo as abandonedCartRepo } from "./abandoned-carts.repository";
export { jsonReturnRepo as returnRepo } from "./returns.repository";
export type { ProductRepository } from "./products.repository";
export type { CategoryRepository } from "./categories.repository";
export type { UserRepository } from "./users.repository";
export type { OrderRepository } from "./orders.repository";
export type { PaymentRepository } from "./payments.repository";
export type { AddressRepository } from "./addresses.repository";
export type { WishlistRepository } from "./wishlists.repository";
export type { CartRepository, UserCart } from "./carts.repository";
export type { ReviewRepository } from "./reviews.repository";
export type { CouponRepository, CouponInput } from "./coupons.repository";
export type { AbandonedCartRepository } from "./abandoned-carts.repository";
export type { ReturnRepository } from "./returns.repository";
